source "http://rubygems.org"

gem "webdrivers"
gem "capybara-selenium"
gem "chromedriver-helper"
gem "rubocop-faker"
gem "capybara"
gem "cucumber", "~> 3.1", ">= 3.1.2"
gem "pry"
gem "rspec"
gem "selenium-webdriver"
gem "faker"
gem "cpf_faker"
